<div data-role="content">

    <script type="text/javascript" src="scripts/essen.js"></script>

    <script type="text/javascript">
        $(document).ready(essen_makeRequest('151807808195576', 'posts'));
    </script>

    <div id="test"></div>
    <table border="1">
        <tr>
            <td colspan="2"><div id="T1" align="center"
                                 style="font-weight: bold; color: white; background-color: #003C78"></div>
            </td>
        </tr>
        <tr>
            <td><b>Gericht</b>
            </td>
            <td><b>Preis</b>
            </td>
        </tr>
        <tr>
            <td><div id="T1e1"></div></td>
            <td><div id="T1p1"></div></td>
        </tr>
        <tr>
            <td><div id="T1e2"></div></td>
            <td><div id="T1p2"></div></td>
        </tr>
        <tr>
            <td><div id="T1e3"></div></td>
            <td><div id="T1p3"></div></td>
        </tr>
        <tr>
            <td><div id="T1e4"></div></td>
            <td><div id="T1p4"></div></td>
        </tr>

        <tr>
            <td colspan="2"><div id="T2" align="center"
                                 style="font-weight: bold; color: white; background-color: #003C78"></div>
            </td>
        </tr>
        <tr>
            <td><b>Gericht</b>
            </td>
            <td><b>Preis</b>
            </td>
        </tr>
        <tr>
            <td><div id="T2e1"></div></td>
            <td><div id="T2p1"></div></td>
        </tr>
        <tr>
            <td><div id="T2e2"></div></td>
            <td><div id="T2p2"></div></td>
        </tr>
        <tr>
            <td><div id="T2e3"></div></td>
            <td><div id="T2p3"></div></td>
        </tr>
        <tr>
            <td><div id="T2e4"></div></td>
            <td><div id="T2p4"></div></td>
        </tr>
    </table>

</div>